# Generated by Django 2.1.2 on 2018-11-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorUser',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
