# Generated by Django 2.1.2 on 2018-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediplyus', '0002_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=130, unique=True),
        ),
    ]
