# Generated by Django 2.1.2 on 2018-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ManyToManyField(blank=True, to='clinic.Clinic'),
        ),
    ]
