# Generated by Django 2.1.2 on 2018-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=130, unique=True)),
                ('number', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
